version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.1-node-browsers
         environment:
           RAILS_ENV: test

    working_directory: ~/repo

    steps:
      - checkout
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: bundle exec rspec
      - run: bundle exec rubocop

workflows:
  version: 2
  test:
    jobs:
      - build
