version: 2.1
jobs:
  build:
    docker:
       - image: cimg/ruby:3.0.5
         environment:
           RAILS_ENV: test

    working_directory: ~/repo

    steps:
      - checkout
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: bundle exec rspec
      - run: bundle exec rubocop

workflows:
  version: 2.1
  test:
    jobs:
      - build
